# NOVA RICS Open Lab 🧊, MIT license

name: 🚀 Feature Request
description: Suggest an idea for the 3D Linear Gripper
# title: " "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a 3D Linear Gripper 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/NOVA-RICS-Open-Lab/3d-linear-gripper/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the 3D Linear Gripper [issues](https://github.com/NOVA-RICS-Open-Lab/3d-linear-gripper/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in 3D Linear Gripper?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/NOVA-RICS-Open-Lab/3d-linear-gripper/pulls) (PR) to help improve the 3D Linear Gripper for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the 3D Linear Gripper [Contributing Guide](https://github.com/NOVA-RICS-Open-Lab/3d-linear-gripper/blob/main/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!